### ISSUE TITLE
报错：Cannot choose from an empty sequence

### ISSUE THREAD

**Issue by Jayce-H** [elliot-bia/God_Dam_Fuck_SMU_Evaluation#1]
Traceback (most recent call last):
  File "C:\Users\dell\Desktop\smu.py", line 553, in <module>
    main()
  File "C:\Users\dell\Desktop\smu.py", line 535, in main
    post_data = html_parse_class.html_pares_index(html_content)
  File "C:\Users\dell\Desktop\smu.py", line 435, in html_pares_index
    score, dt_list = self.get_dt_content(soup)
  File "C:\Users\dell\Desktop\smu.py", line 414, in get_dt_content
    diff_content3 = self.distinguish_question_type3(child)
  File "C:\Users\dell\Desktop\smu.py", line 355, in distinguish_question_type3
    dtjg = self.content_from_txt()
  File "C:\Users\dell\Desktop\smu.py", line 344, in content_from_txt
    return random.choice(content_list)
  File "D:\Python\lib\random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

**Comment by Jayce-H** [comment]
检查发现是439行出错 score, dt_list = self.get_dt_content(soup)

**Comment by Jayce-H** [comment]
已解决，跟进完成
